import { useEffect, useMemo, useRef, useState } from 'react';

const ORIENTATION_KEY = 'liber333_orientation_seen_v1';
const PREFERENCES_KEY = 'liber333_shell_preferences_v1';

const DEFAULT_PREFERENCES = {
  effects: 'balanced',
  motion: 'system',
  textScale: '100',
};

const MODE_LABELS = {
  oracle: 'ORACLE',
  ritual: 'RITES',
  tree: 'TREE',
  gematria: 'GEMATRIA',
  grimoire: 'GRIMOIRE',
};

const PATHS = [
  {
    id: 'ask',
    mode: 'oracle',
    eyebrow: 'ASK',
    glyph: '☉',
    title: 'Bring a Question',
    description:
      'Use the gematria of a sincere question to draw one chapter or a three-part dialectical spread, then receive commentary and an optional AI-assisted reflection.',
    bestFor: 'Decision, contradiction, recurring difficulty, or a situation that needs symbolic reframing.',
    action: 'Begin Consultation',
  },
  {
    id: 'study',
    mode: 'tree',
    eyebrow: 'STUDY',
    glyph: '☷',
    title: 'Enter the Tree',
    description:
      'Browse the chapters through their Qabalistic locations and compare texts deliberately, without treating your selection as a divinatory draw.',
    bestFor: 'Close reading, correspondence study, chapter comparison, and learning the architecture of the Book.',
    action: 'Open the Tree',
  },
  {
    id: 'practice',
    mode: 'ritual',
    eyebrow: 'PRACTICE',
    glyph: '✦',
    title: 'Perform a Rite',
    description:
      'Follow a performable chapter station by station with directions, words, transliteration, symbolic meaning, progress, and optional ritual bells.',
    bestFor: 'Structured practice when you want an operative sequence rather than an interpretation.',
    action: 'View the Rites',
  },
  {
    id: 'calculate',
    mode: 'gematria',
    eyebrow: 'CALCULATE',
    glyph: '∴',
    title: 'Examine a Number',
    description:
      'Calculate English Ordinal gematria, reduction steps, factors, and notable correspondences without initiating a reading.',
    bestFor: 'Testing phrases, comparing names, and investigating numerical echoes before using them elsewhere.',
    action: 'Open Gematria',
  },
  {
    id: 'review',
    mode: 'grimoire',
    eyebrow: 'REVIEW',
    glyph: '☥',
    title: 'Return to Memory',
    description:
      'Review saved readings, recurrence counts, questions, interpretations, timing context, and the long pattern of your work.',
    bestFor: 'Integration after several consultations and identifying lessons the Book repeatedly returns to.',
    action: 'Open the Grimoire',
  },
];

const MODE_HELP = {
  oracle: {
    title: 'Oracle — Chamber of Question',
    glyph: '☉',
    purpose:
      'The Oracle turns a question into a deterministic chapter selection through English Ordinal gematria, then places the source text, editorial commentary, calculated correspondences, and an AI-assisted reflection in one revelation.',
    useWhen:
      'Use it when you can formulate one concrete question. Avoid asking several unrelated questions at once; the numerical key is produced from the exact wording you enter.',
    method:
      'Single draws one chapter from the full corpus. Triad uses three different deterministic indexes and reads them as Thesis, Antithesis, and Synthesis.',
    example:
      'Instead of “Tell me everything,” ask “What attachment is obstructing my work right now?” Then save the result and record the action you will test.',
    provenance:
      'The chapter text is the literary source. The fixed commentary is modern editorial interpretation. Gematria is calculated. The Oracle reflection is generated by an external AI provider when that service is available.',
    data:
      'Your question and selected context are transmitted to the configured AI provider during an Oracle consultation. Saved journal entries remain in this browser’s local storage.',
    next:
      'After the reading, locate the chapter on the Tree, perform its linked rite when available, or save it to the Grimoire and compare future recurrences.',
    actions: [
      { mode: 'tree', label: 'Study the Tree' },
      { mode: 'grimoire', label: 'Review Saved Work' },
    ],
  },
  ritual: {
    title: 'Rites — Processional Circle',
    glyph: '✦',
    purpose:
      'Rites converts the three performable chapters into guided sequences with preparation, stations, spoken words, explanatory notes, and progress.',
    useWhen:
      'Use it when you want to enact a text rather than merely read it. Read the complete rite first, prepare a quiet space, and choose symbolic substitutions that keep the practice physically safe.',
    method:
      'Select a rite, review its introduction, enable sound if you want station bells, then advance only after completing the present instruction.',
    example:
      'Perform the Star Ruby slowly, then write one sentence in your journal describing the change in attention before and after the rite.',
    provenance:
      'The rite sequence is an editorially structured presentation of material associated with the relevant chapter. Explanatory meanings and safety language are editorial additions.',
    data:
      'The guided rite itself is local and does not require the AI service. The current release does not automatically save rite progress or post-rite notes.',
    next:
      'Study the source chapter after the rite, or bring the practical result—not merely the ritual symbolism—into a later Oracle question.',
    actions: [
      { mode: 'tree', label: 'Study Source Chapters' },
      { mode: 'oracle', label: 'Ask After Practice' },
    ],
  },
  tree: {
    title: 'Tree — Map of Emanation',
    glyph: '☷',
    purpose:
      'The Tree organizes the corpus by Sephiroth, paths, and the three negative veils so the Book can be studied as a symbolic architecture rather than a linear list.',
    useWhen:
      'Use it to compare chapters sharing a sphere or path, learn correspondences, or deliberately open a known chapter. A chapter selected here is a study choice, not a random or gematric divination.',
    method:
      'Tap a sphere, path, or the veils. Read the location description, inspect the chapters seated there, and choose one to open in study view.',
    example:
      'Compare several Hod chapters and ask what they share regarding language, analysis, mediation, or the instability of intellect.',
    provenance:
      'The visual map and chapter placements are an editorial correspondence model. They should be treated as interpretive architecture, not as a claim that Crowley supplied this exact interactive arrangement.',
    data:
      'Tree browsing is local. Opening a chapter does not contact the AI service unless you later invoke an Oracle interpretation.',
    next:
      'Send a discovered title or phrase to Gematria, or formulate a question informed by the pattern you observed.',
    actions: [
      { mode: 'gematria', label: 'Examine a Phrase' },
      { mode: 'oracle', label: 'Consult Deliberately' },
    ],
  },
  gematria: {
    title: 'Gematria — Constellation of Number',
    glyph: '∴',
    purpose:
      'Gematria calculates A=1 through Z=26, shows the full sum and reduction chain, and surfaces selected numerical correspondences, factors, squares, and nearby notable values.',
    useWhen:
      'Use it to compare exact spellings, test a phrase before consultation, or understand how the Oracle’s chapter index was formed.',
    method:
      'Only Latin letters are counted. Spaces, punctuation, digits, accents, and other scripts are ignored by the current calculator.',
    example:
      'Calculate two competing formulations of the same intention. Compare the totals, but also compare which wording is more exact and ethically honest.',
    provenance:
      'The arithmetic is reproducible. The meanings attached to notable numbers are editorial selections from Qabalistic and Thelemic reference traditions; numerical resemblance is not historical proof or causation.',
    data:
      'Standalone Gematria calculation occurs entirely in the browser and is not sent to an AI provider.',
    next:
      'Use the clearer phrase as an Oracle question, or investigate chapters and Tree locations associated with the resulting number.',
    actions: [
      { mode: 'oracle', label: 'Use a Question in Oracle' },
      { mode: 'tree', label: 'Browse Correspondences' },
    ],
  },
  grimoire: {
    title: 'Grimoire — Memory Vault',
    glyph: '☥',
    purpose:
      'The Grimoire preserves saved consultations, their questions, chapters, gematria totals, AI interpretations, spread type, and timing context, while tracking recurrence across readings.',
    useWhen:
      'Use it after several consultations. Its value comes from longitudinal comparison rather than collecting isolated revelations.',
    method:
      'Open an entry to revisit it. Compare repeated chapters, the wording of earlier questions, and whether you acted on prior advice before consulting again.',
    example:
      'When a chapter repeats, write down what remained unresolved between appearances. Treat recurrence as a prompt for verification, not automatic supernatural proof.',
    provenance:
      'The journal is a record of your own inputs and app outputs. Milestone language and recurrence framing are part of the application’s designed ritual experience.',
    data:
      'Entries are currently stored in this browser’s local storage. They are not synchronized across devices and can be lost if browser storage is cleared. Export and import are planned but not yet implemented.',
    next:
      'Return to the Oracle only after identifying the exact pattern or unfinished action that your saved work reveals.',
    actions: [
      { mode: 'oracle', label: 'Begin a New Reading' },
      { mode: 'tree', label: 'Study a Recurrent Chapter' },
    ],
  },
};

function normalizeText(value = '') {
  return value
    .replace(/[^\p{L}\p{N}]+/gu, ' ')
    .trim()
    .toUpperCase();
}

function readStoredPreferences() {
  try {
    const parsed = JSON.parse(localStorage.getItem(PREFERENCES_KEY) || 'null');
    return { ...DEFAULT_PREFERENCES, ...(parsed || {}) };
  } catch {
    return DEFAULT_PREFERENCES;
  }
}

function hasSeenOrientation() {
  try {
    return localStorage.getItem(ORIENTATION_KEY) === 'true';
  } catch {
    return false;
  }
}

function findButton(label) {
  const target = normalizeText(label);
  return Array.from(document.querySelectorAll('button')).find((button) => {
    const text = normalizeText(button.textContent || '');
    return text === target || (target === 'GRIMOIRE' && text.startsWith('GRIMOIRE'));
  });
}

function navigateLegacyApp(mode, { beginOracle = false } = {}) {
  window.dispatchEvent(new CustomEvent('liber333:navigate', { detail: { mode, beginOracle } }));

  window.setTimeout(() => {
    findButton(MODE_LABELS[mode])?.click();

    if (mode === 'oracle' && beginOracle) {
      window.setTimeout(() => findButton('BEGIN CONSULTATION')?.click(), 90);
    }
  }, 80);
}

function Modal({ title, description, onClose, children, className = '' }) {
  const dialogRef = useRef(null);
  const titleId = `liber-dialog-${normalizeText(title).toLowerCase().replace(/\s+/g, '-')}`;

  useEffect(() => {
    const previous = document.activeElement;
    const dialog = dialogRef.current;
    const focusable = dialog?.querySelector(
      'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
    );
    focusable?.focus();

    const onKeyDown = (event) => {
      if (event.key === 'Escape') {
        event.preventDefault();
        onClose();
        return;
      }

      if (event.key !== 'Tab' || !dialog) return;
      const items = Array.from(
        dialog.querySelectorAll(
          'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
        ),
      );
      if (!items.length) return;
      const first = items[0];
      const last = items[items.length - 1];
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    };

    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.removeEventListener('keydown', onKeyDown);
      previous?.focus?.();
    };
  }, [onClose]);

  return (
    <div className="liber-shell-backdrop" role="presentation">
      <button className="liber-shell-dismiss-layer" aria-label="Close dialog" onClick={onClose} />
      <section
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={description ? `${titleId}-description` : undefined}
        className={`liber-shell-dialog ${className}`}
      >
        <header className="liber-shell-dialog-header">
          <div>
            <p className="liber-shell-kicker">LIBER CCCXXXIII</p>
            <h2 id={titleId}>{title}</h2>
            {description ? <p id={`${titleId}-description`}>{description}</p> : null}
          </div>
          <button className="liber-shell-close" onClick={onClose} aria-label="Close">
            ×
          </button>
        </header>
        {children}
      </section>
    </div>
  );
}

function Orientation({ onChoose, onDismiss }) {
  return (
    <Modal
      title="How Will You Enter the Book?"
      description="Choose a way of working. This changes your starting point, not the content or calculation of the grimoire."
      onClose={onDismiss}
      className="liber-shell-dialog--wide"
    >
      <div className="liber-path-grid">
        {PATHS.map((path) => (
          <button key={path.id} className="liber-path-card" onClick={() => onChoose(path)}>
            <span className="liber-path-glyph" aria-hidden="true">
              {path.glyph}
            </span>
            <span className="liber-path-eyebrow">{path.eyebrow}</span>
            <strong>{path.title}</strong>
            <span className="liber-path-description">{path.description}</span>
            <span className="liber-path-best">
              <b>Best for:</b> {path.bestFor}
            </span>
            <span className="liber-path-action">{path.action} →</span>
          </button>
        ))}
      </div>
      <div className="liber-shell-note">
        <strong>What stays local?</strong> Tree browsing, Gematria, Rites, and the journal operate in your browser. An Oracle consultation can transmit your question and reading context to the configured AI provider.
      </div>
      <button className="liber-shell-text-action" onClick={onDismiss}>
        Enter without guidance
      </button>
    </Modal>
  );
}

function HelpPanel({ mode, onClose, onNavigate }) {
  const help = MODE_HELP[mode] || MODE_HELP.oracle;
  return (
    <Modal title={help.title} onClose={onClose} className="liber-shell-dialog--medium">
      <div className="liber-help-glyph" aria-hidden="true">
        {help.glyph}
      </div>
      <div className="liber-help-sections">
        <section>
          <h3>Purpose</h3>
          <p>{help.purpose}</p>
        </section>
        <section>
          <h3>When to use it</h3>
          <p>{help.useWhen}</p>
        </section>
        <section>
          <h3>How it works</h3>
          <p>{help.method}</p>
        </section>
        <section>
          <h3>Practical application</h3>
          <p>{help.example}</p>
        </section>
        <section>
          <h3>Source and interpretation</h3>
          <p>{help.provenance}</p>
        </section>
        <section>
          <h3>Data</h3>
          <p>{help.data}</p>
        </section>
        <section className="liber-help-next">
          <h3>What to do next</h3>
          <p>{help.next}</p>
        </section>
      </div>
      <div className="liber-shell-actions">
        {help.actions.map((action) => (
          <button key={action.mode} onClick={() => onNavigate(action.mode)}>
            {action.label}
          </button>
        ))}
      </div>
    </Modal>
  );
}

function SegmentedControl({ label, value, options, onChange }) {
  return (
    <fieldset className="liber-setting-group">
      <legend>{label}</legend>
      <div className="liber-segmented">
        {options.map((option) => (
          <button
            type="button"
            key={option.value}
            aria-pressed={value === option.value}
            className={value === option.value ? 'is-active' : ''}
            onClick={() => onChange(option.value)}
          >
            {option.label}
          </button>
        ))}
      </div>
    </fieldset>
  );
}

function SettingsPanel({ preferences, onChange, onResetOrientation, onClose }) {
  return (
    <Modal
      title="Reading Environment"
      description="These controls change presentation only. They do not alter the text, chapter selection, gematria, journal, or Oracle prompts."
      onClose={onClose}
      className="liber-shell-dialog--medium"
    >
      <div className="liber-settings-stack">
        <SegmentedControl
          label="Visual intensity"
          value={preferences.effects}
          onChange={(effects) => onChange({ ...preferences, effects })}
          options={[
            { value: 'full', label: 'Full' },
            { value: 'balanced', label: 'Balanced' },
            { value: 'low', label: 'Low power' },
          ]}
        />
        <p className="liber-setting-explainer">
          Low power disables the WebGL and particle canvases. Balanced softens them. Full preserves the complete Astral Void treatment.
        </p>

        <SegmentedControl
          label="Motion"
          value={preferences.motion}
          onChange={(motion) => onChange({ ...preferences, motion })}
          options={[
            { value: 'system', label: 'System' },
            { value: 'full', label: 'Full' },
            { value: 'reduced', label: 'Reduced' },
          ]}
        />

        <SegmentedControl
          label="Text scale"
          value={preferences.textScale}
          onChange={(textScale) => onChange({ ...preferences, textScale })}
          options={[
            { value: '90', label: '90%' },
            { value: '100', label: '100%' },
            { value: '115', label: '115%' },
            { value: '130', label: '130%' },
          ]}
        />

        <section className="liber-privacy-card">
          <h3>Privacy and persistence</h3>
          <p>
            Saved readings currently remain in this browser’s local storage. They do not automatically synchronize and can be lost when site data is cleared. Oracle questions and reading context may be sent to the configured AI provider. Tree, Rites, Gematria, and journal review do not require AI.
          </p>
        </section>

        <button className="liber-shell-secondary-action" onClick={onResetOrientation}>
          Show “Ways of Working” again
        </button>
      </div>
    </Modal>
  );
}

export default function ProductShell({ children }) {
  const [orientationOpen, setOrientationOpen] = useState(() => !hasSeenOrientation());
  const [activePanel, setActivePanel] = useState(null);
  const [activeMode, setActiveMode] = useState('oracle');
  const [preferences, setPreferences] = useState(readStoredPreferences);
  const [installPrompt, setInstallPrompt] = useState(null);
  const [installed, setInstalled] = useState(() => window.matchMedia?.('(display-mode: standalone)').matches || false);

  const currentModeLabel = useMemo(() => MODE_LABELS[activeMode] || MODE_LABELS.oracle, [activeMode]);

  useEffect(() => {
    document.documentElement.dataset.liberEffects = preferences.effects;
    document.documentElement.dataset.liberTextScale = preferences.textScale;
    document.documentElement.dataset.liberMotion = preferences.motion;
    document.documentElement.classList.toggle('liber-force-reduced-motion', preferences.motion === 'reduced');
    document.documentElement.classList.toggle('liber-force-full-motion', preferences.motion === 'full');
    try {
      localStorage.setItem(PREFERENCES_KEY, JSON.stringify(preferences));
    } catch {
      // Presentation preferences are non-critical.
    }
  }, [preferences]);

  useEffect(() => {
    const trackMode = (event) => {
      const button = event.target.closest?.('button');
      if (!button) return;
      const text = normalizeText(button.textContent || '');
      const matched = Object.entries(MODE_LABELS).find(([, label]) => {
        const normalizedLabel = normalizeText(label);
        return text === normalizedLabel || (label === 'GRIMOIRE' && text.startsWith(normalizedLabel));
      });
      if (matched) setActiveMode(matched[0]);
    };
    document.addEventListener('click', trackMode, true);
    return () => document.removeEventListener('click', trackMode, true);
  }, []);

  useEffect(() => {
    const beforeInstall = (event) => {
      event.preventDefault();
      setInstallPrompt(event);
    };
    const appInstalled = () => {
      setInstalled(true);
      setInstallPrompt(null);
    };
    window.addEventListener('beforeinstallprompt', beforeInstall);
    window.addEventListener('appinstalled', appInstalled);
    return () => {
      window.removeEventListener('beforeinstallprompt', beforeInstall);
      window.removeEventListener('appinstalled', appInstalled);
    };
  }, []);

  const markOrientationSeen = () => {
    try {
      localStorage.setItem(ORIENTATION_KEY, 'true');
    } catch {
      // Orientation can still close when storage is unavailable.
    }
    setOrientationOpen(false);
  };

  const choosePath = (path) => {
    markOrientationSeen();
    setActiveMode(path.mode);
    navigateLegacyApp(path.mode, { beginOracle: path.id === 'ask' });
  };

  const navigate = (mode) => {
    setActivePanel(null);
    setActiveMode(mode);
    navigateLegacyApp(mode, { beginOracle: false });
  };

  const install = async () => {
    if (!installPrompt) return;
    await installPrompt.prompt();
    await installPrompt.userChoice.catch(() => null);
    setInstallPrompt(null);
  };

  return (
    <>
      {children}

      {!orientationOpen ? (
        <div className="liber-utility-rail" aria-label="Grimoire guidance and settings">
          <button
            onClick={() => setActivePanel('help')}
            aria-label={`Explain ${currentModeLabel.toLowerCase()} mode`}
            title={`Explain ${currentModeLabel.toLowerCase()} mode`}
          >
            <span aria-hidden="true">?</span>
            <small>{currentModeLabel}</small>
          </button>
          <button onClick={() => setActivePanel('settings')} aria-label="Open reading environment settings" title="Reading environment">
            <span aria-hidden="true">⚙</span>
            <small>SETTINGS</small>
          </button>
          {!installed && installPrompt ? (
            <button onClick={install} aria-label="Install Liber 333" title="Install Liber 333">
              <span aria-hidden="true">⇩</span>
              <small>INSTALL</small>
            </button>
          ) : null}
        </div>
      ) : null}

      {orientationOpen ? <Orientation onChoose={choosePath} onDismiss={markOrientationSeen} /> : null}
      {activePanel === 'help' ? <HelpPanel mode={activeMode} onClose={() => setActivePanel(null)} onNavigate={navigate} /> : null}
      {activePanel === 'settings' ? (
        <SettingsPanel
          preferences={preferences}
          onChange={setPreferences}
          onResetOrientation={() => {
            try {
              localStorage.removeItem(ORIENTATION_KEY);
            } catch {
              // Non-critical.
            }
            setActivePanel(null);
            setOrientationOpen(true);
          }}
          onClose={() => setActivePanel(null)}
        />
      ) : null}
    </>
  );
}
