// Stable editorial tables used by the current English Ordinal calculator.
// Values and wording are intentionally unchanged from the original monolith.

export const ENGLISH_QABALAH = {
  a:1, b:2, c:3, d:4, e:5, f:6, g:7, h:8, i:9, j:10,
  k:11, l:12, m:13, n:14, o:15, p:16, q:17, r:18, s:19, t:20,
  u:21, v:22, w:23, x:24, y:25, z:26
};

export const NOTABLE_NUMBERS = {
  0:   "Ain (אין) — Nothing; the Negative Veils",
  1:   "Kether; Aleph; the Point",
  2:   "Chokmah; Beth; duality",
  3:   "Binah; Gimel; the Triangle",
  5:   "Geburah; Hé; the Pentagram",
  6:   "Tiphareth; Vau; the Hexagram",
  7:   "Netzach; Zayin; Venus; the 7 Palaces",
  8:   "Hod; Cheth; Mercury",
  9:   "Yesod; Teth; the Moon",
  10:  "Malkuth; Yod; the Kingdom; the complete Tree",
  11:  "Magick; Abrahadabra has 11 letters; the Qliphoth",
  12:  "HVA (הוא) — He/She/It; the Zodiac has 12 signs",
  13:  "AChD (אחד) — Unity; AHBH (אהבה) — Love",
  14:  "DVD (דוד) — David, Beloved; ZHB (זהב) — Gold",
  15:  "YH (יה) — Yah, divine name; the Devil (XV)",
  17:  "ChVH (חוה) — Eve; IAO; a holy prime",
  18:  "ChY (חי) — Life, Living",
  20:  "YVD (יוד) — Yod spelled in full (the Hand)",
  21:  "AHYH (אהיה) — Eheieh ('I Am'), name of Kether",
  22:  "The 22 Hebrew letters; 22 paths on the Tree",
  23:  "ChYH (חיה) — Life-force; ChDVH — Joy; '23 Skidoo'",
  25:  "5² — the Pentagram squared",
  26:  "YHVH (יהוה) — Tetragrammaton, the Demiurge",
  28:  "KCh (כח) — Power; sum of 1–7 (mystic number of Netzach)",
  31:  "AL (אל) — God; LA (לא) — Not; the key reversal",
  32:  "LB (לב) — Heart/Mind; 32 paths on the Tree",
  33:  "GL (גל) — Spring, fountain; 33rd Masonic degree",
  36:  "6² — Hexagram squared; ALH (אלה) — Goddess",
  37:  "YChYDH (יחידה) — Yechidah, True Will; HBL — Vanity",
  39:  "YHVH AChD — 'The Lord is One'; TAL (טל) — Dew",
  40:  "Mem (מ) — Water; 40 days of the Flood",
  42:  "AMA (אמא) — unfertilized Mother; the 42-letter Name",
  44:  "DM (דם) — Blood; the Mass of the Phoenix",
  45:  "ADM (אדם) — Adam; MH (מה) — What?",
  49:  "7² — Venus squared",
  50:  "KL (כל) — All, Everything; the 50 Gates of Binah",
  52:  "BN (בן) — Son; AYMA (אימא) — fertile Mother",
  53:  "ABN (אבן) — Stone = AB (Father) + BN (Son); GN — Garden",
  55:  "KLH (כלה) — Bride (Malkuth); sum of 1–10",
  56:  "YVM (יום) — Day",
  58:  "ChN (חן) — Grace, beauty, favor",
  61:  "AYN (אין) — Nothing = ANY (אני) — I; Nothing = Ego",
  64:  "DYN (דין) — Judgment; 8²",
  65:  "ADNY (אדני) — Adonai, the Holy Guardian Angel; HS — Silence!; HYKL — Temple",
  66:  "Sum of 1–11 (mystic number of Qliphoth); the Great Work",
  67:  "BYNH (בינה) — Binah, Understanding",
  68:  "ChYYM (חיים) — Life (lives); ChKM — Wise",
  70:  "Ayin (ע) — Eye; YYN — Wine; SVD — Secret",
  72:  "ChSD (חסד) — Chesed, Mercy; the 72-fold Name of God",
  73:  "ChKMH (חכמה) — Chokmah, Wisdom; GML — Gimel/Camel",
  77:  "OZ (עז) — Strength, a Goat; MZLA — Influence from Kether",
  78:  "LCHM (לחם) — Bread; MZL — Mazal; 78 Tarot cards",
  80:  "Pé (פ) — Mouth; YSVD — Yesod",
  81:  "9² (3⁴); ANKY (אנכי) — I (emphatic); KSA — Throne",
  86:  "ALHYM (אלהים) — Elohim; AHYH+ADNY (21+65) = Kether+Malkuth",
  89:  "GVP (גוף) — Body; DMMH — Silence ('still small voice')",
  90:  "MYM (מים) — Water; Tzaddi = 90; MLK — King",
  91:  "AMN (אמן) — Amen = YHVH(26) + ADNY(65); sum of 1–13",
  93:  "Thelema (θελημα) — Will; Agape (αγαπη) — Love; the Law",
  100: "Qoph (ק); KP — Palm; MLKVTh first letters",
  111: "ALP (אלף) — Aleph spelled fully; APL — thick darkness; AChD HVA ALHYM — 'He is One God'",
  120: "MVSDI — Foundation; Samekh spelled fully; 5! (factorial)",
  131: "Samael (סמאל) — the Poison of God",
  156: "BABALON (באבאלון); 12×13; Zion",
  165: "MKPAL (מקפאל) — the 'beating' of God",
  175: "Sum of Venus magic square (7×25)",
  200: "Resh (ר) — Head; the Sun",
  206: "DBR (דבר) — Word; RVCh ALHYM — Spirit of God",
  210: "Sum of 1–20; NOX",
  220: "Liber AL vel Legis (Book of the Law); 10×22",
  231: "The 231 Gates of the Sepher Yetzirah",
  260: "TIRION — Tiriel (Mercury intelligence); 10×YHVH",
  280: "MNTzPK — the 5 final letters; Sandalphon; RP — healing",
  300: "Shin (ש) — Tooth/Fire; RVCh ALHYM — Spirit of Elohim",
  314: "ShDY (שדי) — Shaddai, the Almighty; Metatron",
  325: "Sum of 1–25; BRKSh — a first-born",
  326: "IHShVH (יהשוה) — Yeheshuah, Jesus (Pentagrammaton)",
  333: "ChVRVNZVN (חורונזון) — Choronzon, Demon of the Abyss; 3×111",
  340: "ShM (שם) — The Name (in full: Shin+Mem)",
  358: "MShYCh (משיח) — Messiah; NChSh (נחש) — Serpent",
  361: "19²; AShNTh — a Woman",
  365: "Abraxas (Αβραξας); Metatron; days of the solar year",
  370: "OShN (עשן) — Smoke; ShLM — perfection, peace (Shalem)",
  393: "Sum of paths on Tree in one tradition",
  400: "Tau (ת) — Cross; the last Hebrew letter",
  401: "ATh (את) — Essence; Alpha and Omega",
  418: "ABRAHADABRA (אברהדברא) — Word of the Aeon; ChYTh — Beast (living creature)",
  434: "DLTh (דלת) — Daleth spelled fully (Door)",
  440: "ThM (תם) — Completeness, Perfection; MT — Dead",
  444: "DM squared; Blood of the Saints; MKDSh — Sanctuary",
  463: "Longest diagonal of Tree of Life",
  474: "DOTh (דעת) — Daath, Knowledge",
  500: "Kaph final (ך); ShR — Prince; ThK — Centre",
  510: "RYSh (ריש) — Resh spelled fully (Head of the Sun)",
  543: "AHYH AShR AHYH — 'I Am That I Am'",
  620: "KThR (כתר) — Kether spelled fully (Crown)",
  640: "ShMSh (שמש) — Sun (Shemesh); ThMYM — Perfections",
  666: "SVRTh (סורת) — Sorath, Spirit of the Sun; Number of the Beast; sum of 1–36 (magic square of Sol)",
  671: "ThORA (תערא) — the Gate; ThORA — Torah",
  700: "Nun final (ן); ThSh — foundation",
  718: "Stélé of Revealing (number of the Stele at Boulaq Museum)",
  741: "AMTh (אמת) — Truth (Aleph+Mem+Tau in full)",
  777: "OLM HQLYPVTh — World of Shells (a reading); the Flaming Sword descending through all paths; Crowley's key reference work",
  800: "Pé final (ף); QShTh — the Rainbow",
  813: "ARAShITh — 'In the Beginning'",
  831: "PhLG (פלג) — division; the Phallus",
  888: "IHSoUS (Ιησους) — Jesus in Greek gematria",
  900: "Tzaddi final (ץ); QTz — summer, end",
  999: "Sum of 1–37 = 703... (actually just a variant trinity of 333×3)",
  1000: "Aleph final (א large); the Thousandfold",
};
